//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecruitmentApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appliant
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string TC { get; set; }
        public string Years { get; set; }
        public string Skill { get; set; }
        public string ExperienceYear { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int StatusId { get; set; }
        public int ResultsId { get; set; }
    
        public virtual Result Result { get; set; }
        public virtual Status Status { get; set; }
    }
}
